#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: atm-signature-southern-ocn-co2 # The title of the book. Will be placed in the left navbar.
author: Matt Long, Britt Stephens # The author of the book
copyright: '2021' # Copyright year to be placed in the footer
logo: logo.png # A path to the book logo
